name: Main CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  SKIP_ENV_VALIDATION: "true"
  NEXT_PUBLIC_DISABLE_DEVTOOLS: "true"
  NEXT_PUBLIC_WEBSITE_URL: "http://localhost:3000"
  SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_RELEASE: ${{ secrets.SENTRY_RELEASE }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:
  build:
    name: Bun CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Typegen
        run: bun run typegen

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Tests
        run: bun run test

      - name: Build
        run: bun run build
